tasks:
  - init: yarn install && yarn run build
    command: yarn run start

vscode:
  extensions:
    - unifiedjs.vscode-mdx

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true

ports:
  - name: Preview
    port: 3000
    visibility: public
    onOpen: open-browser
